INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (1, 'Гарата се намира на теснолинейната жп линияп Септември-Добринище и е най-високата гара на Балканите', 'Аврамово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (4, null, 'Айтос', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (5, null, 'Алдомировци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (6, null, 'Антон', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (7, null, 'Асеновград', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (8, null, 'Аспарухово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (9, null, 'Банкя', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (10, null, 'Банско', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (11, null, 'Баня', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (12, null, 'Батановци', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (13, null, 'Безмер', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (14, null, 'Бели Извор', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (15, null, 'Белица', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (16, null, 'Белово', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (17, null, 'Белозем', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (18, null, 'Белослав', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (19, null, 'Берковица', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (20, null, 'Благоевград', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (21, null, 'Бобов дол', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (22, null, 'Бобошево', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (23, null, 'Бов', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (24, null, 'Бойчиновци', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (25, null, 'Борово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (26, null, 'Ботев', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (27, null, 'Брацигово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (28, null, 'Брусарци', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (29, null, 'Бургас', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (30, null, 'Българово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (31, null, 'Бяла', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (32, null, 'Вакарел', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (33, null, 'Варвара', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (34, null, 'Варна', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (35, null, 'Велико Търново', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (36, null, 'Велинград', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (37, null, 'Величково', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (38, null, 'Веринско', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (39, null, 'Ветово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (40, null, 'Видин пътническа', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (41, null, 'Видин товарна', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (42, null, 'Висока поляна', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (43, null, 'Владая', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (44, null, 'Владимир Павлов', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (45, null, 'Волуяк', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (46, null, 'Враца', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (47, null, 'Вълчи дол', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (48, null, 'Габрово', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (49, null, 'Гавраилово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (50, null, 'Генерал Тодоров', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (51, null, 'Голямо село', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (52, null, 'Горна баня', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (53, null, 'Горна Оряховица', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (54, null, 'Горни дъбник', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (55, null, 'Граф Игнатиево', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (56, null, 'Гурково', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (57, null, 'Гюешево', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (58, null, 'Дамяница', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (59, null, 'Две Могили', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (60, null, 'Дебелец', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (61, null, 'Девня', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (62, null, 'Делян', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (63, null, 'Джулюница', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (64, null, 'Димитровград', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (65, null, 'Димитровград север', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (66, null, 'Димово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (67, null, 'Добринище', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (68, null, 'Добрич', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (69, null, 'Добрич север', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (70, null, 'Дойренци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (71, null, 'Долапите', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (72, null, 'Долене', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (73, null, 'Долна Махала', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (74, null, 'Долна Митрополия', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (75, null, 'Долни Дъбник', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (76, null, 'Долни Раковец', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (77, null, 'Долно Езерово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (78, null, 'Долно Камарци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (79, null, 'Драгичево', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (80, null, 'Драгоман', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (81, null, 'Дралфа', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (82, null, 'Дреновец', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (83, null, 'Дружба', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (84, null, 'Дряново', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (85, null, 'Дулово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (86, null, 'Дунавци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (87, null, 'Дупница', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (88, null, 'Дъбово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (89, null, 'Дългопол', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (90, null, 'Дъскотна', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (91, null, 'Дяково', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (92, null, 'Езерово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (93, null, 'Елин Пелин', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (94, null, 'Елисейна', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (95, null, 'Желю войвода', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (96, null, 'Завет', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (97, null, 'Завой', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (98, null, 'Захарна фабрика', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (99, null, 'Зверино', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (100, null, 'Земен', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (101, null, 'Зимница', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (102, null, 'Златица', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (103, null, 'Змейово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (104, null, 'Иваново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (105, null, 'Илиянци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (106, null, 'Искър', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (107, null, 'Исперих', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (108, null, 'Ихтиман', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (109, null, 'Казанлък', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (110, null, 'Казичене', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (111, null, 'Калитиново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (112, null, 'Калофер', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (113, null, 'Калояновец', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (114, null, 'Калояново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (115, null, 'Караджалово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (116, null, 'Кардам', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (117, null, 'Карлово', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (118, null, 'Карлуково', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (119, null, 'Карнобат', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (120, null, 'Каспичан', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (121, null, 'Катуница', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (122, null, 'Кермен', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (123, null, 'Клисура', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (124, null, 'Комунари', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (125, null, 'Коньово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (126, null, 'Копривщица', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (127, null, 'Костандово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (128, null, 'Костенец', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (129, null, 'Костинброд', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (130, null, 'Кочериново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (131, null, 'Кремиковци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (132, null, 'Кресна', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (133, null, 'Криводол', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (134, null, 'Крумово', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (135, null, 'Кръстец', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (136, null, 'Кулата', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (137, null, 'Кунино', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (138, null, 'Курило', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (139, null, 'Кърджали', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (140, null, 'Кюстендил', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (141, null, 'Лакатник', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (142, null, 'Левски', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (143, null, 'Ловеч', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (144, null, 'Лозарево', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (145, null, 'Лом', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (146, null, 'Любимец', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (147, null, 'Макоцево', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (148, null, 'Маноле', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (149, null, 'Медковец', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (150, null, 'Мездра', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (151, null, 'Мездра юг', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (152, null, 'Меричлери', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (153, null, 'Мирково', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (154, null, 'Михайлово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (155, null, 'Момчилград', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (156, null, 'Монтана', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (157, null, 'Морава', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (158, null, 'Моруница', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (159, null, 'Мост', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (160, null, 'Мърчево', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (161, null, 'Мътница', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (162, null, 'Нова Загора', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (163, null, 'Нова надежда', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (164, null, 'Образцов чифлик', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (165, null, 'Огняново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (166, null, 'Ореш', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (167, null, 'Орешец', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (168, null, 'Оризово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (169, null, 'Павликени', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (170, null, 'Пазарджик', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (171, null, 'Панагюрище', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (172, null, 'Перник', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (173, null, 'Перник разпределителна', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (174, null, 'Петко Каравелов', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (175, null, 'Петрич', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (176, null, 'Петърч', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (177, null, 'Пещера', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (178, null, 'Пейо Яворов', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (179, null, 'Пирдоп', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (180, null, 'Плачковци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (181, null, 'Плевен', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (182, null, 'Плевен запад', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (183, null, 'Плиска', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (184, null, 'Пловдив', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (185, null, 'Повеляново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (186, null, 'Подвис', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (187, null, 'Подкова', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (188, null, 'Подуяне пътническа', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (189, null, 'Поликраище', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (190, null, 'Полски тръмбеш', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (191, null, 'Поповица', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (192, null, 'Попово', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (193, null, 'Пордим', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (194, null, 'Провадия', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (195, null, 'Просторно', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (196, null, 'Първомай', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (197, null, 'Радомир', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (198, null, 'Радунци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (199, null, 'Раждавица', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (200, null, 'Разград', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (201, null, 'Разделна', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (202, null, 'Разлог', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (203, null, 'Разменна', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (204, null, 'Реброво', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (205, null, 'Ресен', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (206, null, 'Роман', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (207, null, 'Русе разпределителна', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (208, null, 'Русе', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (209, null, 'Руска бяла', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (210, null, 'Самоводене', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (211, null, 'Самуил', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (212, null, 'Сандански', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (213, null, 'Саранци', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (214, null, 'Сахране', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (215, null, 'Световрачене', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (216, null, 'Свиленград', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (217, null, 'Свищов', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (218, null, 'Свобода', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (219, null, 'Своге', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (220, null, 'Сеново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (221, null, 'Септември', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (222, null, 'Силистра', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (223, null, 'Симеоновград', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (224, null, 'Симитли', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (225, null, 'Синдел', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (226, null, 'Скутаре', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (227, null, 'Славяново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (228, null, 'Сливен', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (229, null, 'Сливница', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (230, null, 'Смядово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (231, null, 'Сомовит - М', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (232, null, 'Сопот', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (233, null, 'София', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (234, null, 'София север', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (235, null, 'Срацимир', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (236, null, 'Стамболийски', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (237, null, 'Стара Загора', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (238, null, 'Столник', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (239, null, 'Стражица', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (240, null, 'Стралджа', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (241, null, 'Струмяни', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (242, null, 'Стряма', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (243, null, 'Суворово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (244, null, 'Съединение', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (245, null, 'Твърдица', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (246, null, 'Телиш', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (247, null, 'Тодор Каблешков', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (248, null, 'Тополите', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (249, null, 'Тракия', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (250, null, 'Троян', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (251, null, 'Труд', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (252, null, 'Трявна', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (253, null, 'Тулово', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (254, null, 'Тъжа', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (255, null, 'Търговище', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (256, null, 'Търнак', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (257, null, 'Филипово', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (258, null, 'Хан Аспарух', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (259, null, 'Хан Крум', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (260, null, 'Харманли', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (261, null, 'Хасково', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (262, null, 'Хисар', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (263, null, 'Хитрино', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (264, null, 'Храбърско', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (265, null, 'Христо Даново', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (266, null, 'Царева ливада', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (267, null, 'Цветино', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (268, null, 'Церковски', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (269, null, 'Червен бряг', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (270, null, 'Черганово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (271, null, 'Черквица', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (272, null, 'Черниче', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (273, null, 'Черноград', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (274, null, 'Чирпан', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (275, null, 'Шивачево', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (276, null, 'Шумен', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (277, null, 'Юнак', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (278, null, 'Ябълково', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (279, null, 'Якоруда', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (280, null, 'Ямбол', 'STATION', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (281, null, 'Яна', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (282, null, 'Янтра', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (283, null, 'Ясен', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (284, null, 'Ястребово', 'STATION', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (285, null, 'Александър Димитров', 'RP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (286, null, 'Прилеп', 'RP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (287, null, 'Видбол', 'RP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (288, null, 'Гълъбник', 'RP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (289, null, 'Копиловци', 'RP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (290, null, 'Ловеч север', 'RP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (291, null, 'Лозово', 'RP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (292, null, 'Люляково', 'RP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (422, null, 'Умляк', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (423, null, 'Драгоман спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (424, null, 'Сливница спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (425, null, 'Костинброд спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (426, null, 'Обеля', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (427, null, 'Връбница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (428, null, 'Надежда', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (429, null, 'Подуяне разпределителна среден район', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (430, null, 'Смирненски', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (431, null, 'Искърско шосе', 'STOP', true);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (432, null, 'Верила', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (433, null, 'Побит камък', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (434, null, 'Вакарел спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (435, null, 'Живково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (436, null, 'Стамболово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (437, null, 'Немирово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (438, null, 'Момин проход', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (439, null, 'Бойка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (440, null, 'Сестримо', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (441, null, 'Момина Клисура', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (442, null, 'Благой Захариев', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (443, null, 'Ковачево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (444, null, 'Звъничево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (445, null, 'Мокрище', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (446, null, 'Синитово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (447, null, 'Хаджиево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (448, null, 'Кадиево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (449, null, 'Прослав', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (450, null, 'Вр депо Пловдив', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (451, null, 'Ягодово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (452, null, 'Кочево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (453, null, 'Садово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (454, null, 'Чешнигирово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (455, null, 'Виница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (456, null, 'Скобелево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (457, null, 'Сталево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (458, null, 'Крум', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (459, null, 'Черногорово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (460, null, 'Констнатиново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (461, null, 'Преславец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (462, null, 'Харманли центрлална', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (463, null, 'Бисер', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (464, null, 'Божурище', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (465, null, 'Иваняне', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (466, null, 'Лазар Пампоров', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (467, null, 'Марко Николов', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (468, null, 'Цепина', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (469, null, 'Велинград юг', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (470, null, 'Острец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (471, null, 'Света Петка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (472, null, 'Стоян Митов', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (473, null, 'Смолево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (474, null, 'Черна места', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (475, null, 'Ягорудска минерална баня', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (476, null, 'Юруково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (477, null, 'Дагоново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (478, null, 'Генерал Ковачев', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (479, null, 'Гулийна баня', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (480, null, 'Свети Георги', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (481, null, 'Кричим', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (482, null, 'Козарско', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (483, null, 'Бяга', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (484, null, 'Маврудово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (485, null, 'Кумарица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (486, null, 'Ромча', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (487, null, 'Владо Тричков', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (488, null, 'Луково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (489, null, 'Томпсън', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (490, null, 'Орлин', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (491, null, 'Желен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (492, null, 'Церово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (493, null, 'Балкан', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (494, null, 'жп школа Лакатник', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (495, null, 'Оплетня', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (496, null, 'Левище', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (497, null, 'Пролет', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (498, null, 'Оселна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (499, null, 'Черепиш', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (500, null, 'Люти брод', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (501, null, 'Ребърково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (502, null, 'Горна Крета', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (503, null, 'Брусен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (504, null, 'Ослен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (505, null, 'Синьо Бърдо', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (506, null, 'Струпец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (507, null, 'Радовене', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (508, null, 'Реселец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (509, null, 'Рупци север', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (510, null, 'Хумата', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (511, null, 'Гривица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (512, null, 'Одърне', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (513, null, 'Каменец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (514, null, 'Градище', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (515, null, 'Бутово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (516, null, 'Михалци Стамболово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (517, null, 'Лесичери', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (518, null, 'Русаля Дичин', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (519, null, 'Честово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (520, null, 'Козаревец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (521, null, 'Кесарово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (522, null, 'Асеново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (523, null, 'Горица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (524, null, 'Медовина', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (525, null, 'Светлен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (526, null, 'Караджата', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (527, null, 'Стамо Костов', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (528, null, 'Голямо ново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (529, null, 'Подгорица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (530, null, 'Здравец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (531, null, 'Въбел', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (532, null, 'Васил Левски', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (533, null, 'Ловец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (534, null, 'Надарево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (535, null, 'Кочово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (536, null, 'Дивдядово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (537, null, 'Тракия спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (538, null, 'Мадара', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (539, null, 'Калугерица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (540, null, 'Невша', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (541, null, 'Равна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (542, null, 'Венчан', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (543, null, 'Добрина', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (544, null, 'Столна мина', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (545, null, 'Житница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (546, null, 'Царевци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (547, null, 'Тръстиково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (548, null, 'Страшимирово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (549, null, 'Моряк', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (550, null, ' Езерово спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (551, null, 'Варна спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (552, null, 'Чифлик', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (553, null, 'Божурица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (554, null, 'Подем', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (555, null, 'Комарево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (556, null, 'Крета', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (557, null, 'Милковица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (558, null, 'Долни Вит', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (559, null, 'Елит', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (560, null, 'Драгомирово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (561, null, 'Асеновци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (562, null, 'Летница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (563, null, 'Чавдарци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (564, null, 'Александрово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (565, null, 'Драсов', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (566, null, 'Йоглав', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (567, null, 'Умаревци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (568, null, 'Ловеч спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (569, null, 'Ловеч юг', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (570, null, 'Козачево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (571, null, 'Хлевене', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (572, null, 'Абланица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (573, null, 'Лешница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (574, null, 'Ломец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (575, null, 'Добродан', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (576, null, 'Калейца', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (577, null, 'Дибич', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (578, null, 'Радко Димитриево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (579, null, 'Ивански', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (580, null, 'Бял бряг', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (581, null, 'Желъд', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (582, null, 'Арковна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (583, null, 'Партизани', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (584, null, 'Кипра', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (585, null, 'Чернево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (586, null, 'Генерал Киселово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (619, null, 'Оборище', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (620, null, 'Ботево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (621, null, 'Дончево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (622, null, 'Генерал Колево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (623, null, 'Равнец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (624, null, 'Генерал тошево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (625, null, 'Кубратово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (626, null, 'Негован', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (627, null, 'Локорско', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (628, null, 'Ботунец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (629, null, 'Равно поле', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (630, null, 'Горна малина', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (631, null, 'Негушево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (632, null, 'Чеканчево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (633, null, 'Макоцево спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (634, null, 'Буново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (635, null, 'Мирково спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (636, null, 'Челопеч', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (637, null, 'Розино', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (638, null, 'Кърнаре', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (639, null, 'Иганово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (640, null, 'Анево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (641, null, 'Свежен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (642, null, 'Осетеново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (643, null, 'Манолово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (644, null, 'Търничени', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (645, null, 'Габарево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (646, null, 'Павел баня', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (647, null, 'Голямо Дряново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (648, null, 'Ветрен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (649, null, 'Николаево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (650, null, 'Сборище', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (651, null, 'Чумерна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (652, null, 'Орешак', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (653, null, 'Селиминово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (654, null, 'Чинтулово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (655, null, 'Таню войвода', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (656, null, 'Невестино', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (657, null, 'Вълчин', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (658, null, 'Климаш', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (659, null, 'Ведрово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (660, null, 'Завет спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (661, null, 'Листец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (662, null, 'Дропла', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (663, null, 'Каравельово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (664, null, 'Струя', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (665, null, 'Боряна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (666, null, 'Нова шипка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (667, null, 'Товарна гара', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (668, null, 'Божичен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (669, null, 'Кошов', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (670, null, 'Табачка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (671, null, 'Батишница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (672, null, 'Стърмен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (673, null, 'Полско Косово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (674, null, 'Раданово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (675, null, 'Полски сеновец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (676, null, 'Куцина', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (677, null, 'Крушето', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (678, null, 'Правда', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (679, null, 'Трапезица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (680, null, 'Дълга лъка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (681, null, 'Соколово спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (682, null, 'Ганчовец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (683, null, 'Дряново спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (684, null, 'Бачо Киро', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (685, null, 'Стайновци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (686, null, 'Божковци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (687, null, 'Радевци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (688, null, 'Бъзовец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (689, null, 'Борущица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (690, null, 'Яворовец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (691, null, 'Ягода', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (692, null, 'Димитриево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (693, null, 'Меричлери спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (694, null, 'Узунджово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (695, null, 'Малево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (696, null, 'Книжовник', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (697, null, 'Царева поляна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (698, null, 'Маслиново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (699, null, 'Добриново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (700, null, 'Мъдрец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (701, null, 'Перперек', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (702, null, 'Калояновци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (703, null, 'Средна Арда', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (704, null, 'Звезделина', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (705, null, 'Широко поле', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (706, null, 'Момина скала', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (707, null, 'Желязна врата', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (708, null, 'Глухар', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (709, null, 'Джебел', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (710, null, 'Горско дюлево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (711, null, 'Птичар', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (712, null, 'Рогозче', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (713, null, 'Стойчевци ', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (714, null, 'Съботковци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (715, null, 'Иванковци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (718, null, 'Горна баня спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (719, null, 'Даскалово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (720, null, 'Метал', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (721, null, 'Кракра спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (722, null, 'Бела вода', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (723, null, 'Копаница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (724, null, 'Кошарите', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (725, null, 'Кондофрей', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (726, null, 'Чуковец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (727, null, 'Марек', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (728, null, 'Яхиново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (729, null, 'Дупница спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (730, null, 'Джерман', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (731, null, 'Усойка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (732, null, 'Мурсалево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (733, null, 'Бело поле', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (734, null, 'Благоевград спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (735, null, 'Железница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (736, null, 'Стара кресна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (737, null, 'Кресна сп', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (738, null, 'Градешница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (739, null, 'Плоски', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (740, null, 'Марикостино', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (741, null, 'Марино поле', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (742, null, 'Рупите', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (743, null, 'Мулетарово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (744, null, 'Мало село', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (745, null, 'Мламолево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (746, null, 'Банковица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (747, null, 'Бригадир', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (748, null, 'Хераково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (749, null, 'Златуша', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (750, null, 'Бригадирска слава', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (751, null, 'Разменна сп', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (752, null, 'Радуй', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (753, null, 'Прибой', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (754, null, 'Дебели лак', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (755, null, 'Егълница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (756, null, 'Калица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (757, null, 'Жабляно', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (758, null, 'Скакавица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (759, null, 'Шишковци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (760, null, 'Соволяно', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (761, null, 'Мазарачево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (762, null, 'Кършалево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (763, null, 'Дождевица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (764, null, 'Церовица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (765, null, 'Леска', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (766, null, 'Кутугерица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (767, null, 'Долно село', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (768, null, 'Преколница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (769, null, 'Моравица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (770, null, 'Враца спирка', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (771, null, 'Власатица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (772, null, 'Ракево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (773, null, 'Пали лула', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (774, null, 'Охрид', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (775, null, 'Габровница', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (776, null, 'Долно Церовене', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (777, null, 'Дъбова махала', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (778, null, 'Воднянци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (779, null, 'Скомля', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (780, null, 'Белщица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (781, null, 'Макреш', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (782, null, 'Жеглица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (783, null, 'Синаговци - Гурково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (784, null, 'Слана бара', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (785, null, 'Ерден', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (786, null, 'Благово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (787, null, 'Боровци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (788, null, 'Бокиловци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (789, null, 'Крива бара', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (790, null, 'Василовци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (791, null, 'Сталийска махала', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (792, null, 'Трайково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (793, null, 'Момин брод', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (794, null, 'Опълченец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (795, null, 'Черна гора', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (796, null, 'Спасово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (797, null, 'Самуилово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (798, null, 'Християново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (799, null, 'Еленино', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (800, null, 'Горно Ботево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (801, null, 'Плоска могила', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (802, null, 'Бозаджии', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (803, null, 'Атолово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (804, null, 'Глумче', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (805, null, 'Кликач', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (806, null, 'Тополица', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (807, null, 'Карагеоргиево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (808, null, 'Каменни кариери', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (809, null, 'Камено', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (810, null, 'Бургас разпределителна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (811, null, 'Бургас товарна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (812, null, 'Царацово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (813, null, 'Бенковски', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (814, null, 'Тополов дол', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (815, null, 'Овчеполци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (816, null, 'Цар Асен', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (817, null, 'Смилец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (818, null, 'Дюлево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (819, null, 'Стрелча', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (820, null, 'Чернозем', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (821, null, 'Горна махала', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (822, null, 'Иван Вазово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (823, null, 'Песнопой', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (824, null, 'Светлина', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (825, null, 'Отдих', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (826, null, 'Дъбене', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (827, null, 'Черничево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (828, null, 'Гълъбово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (829, null, 'Любеново', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (830, null, 'Любенова махала', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (831, null, 'Червена вода', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (832, null, 'Кривня', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (833, null, 'Раковски сп', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (834, null, 'Ясеновец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (835, null, 'Байково', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (836, null, 'Каменяк', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (837, null, 'Златна нива', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (838, null, 'Хърсово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (839, null, 'Голяма вода', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (840, null, 'Богданци', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (841, null, 'Бърдоква', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (842, null, 'Голям поровец', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (843, null, 'Китанчево', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (844, null, 'Тодорово', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (845, null, 'Безименна', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (846, null, 'Руйно', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (847, null, 'Черник', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (848, null, 'Межден', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (849, null, 'Климатично училище', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (850, null, 'Алфатар', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (851, null, 'Бръчма', 'STOP', false);
INSERT INTO railwaydb.stations (id, description, name, station_type, tickets_sale) VALUES (852, null, 'Калипетрово', 'STOP', false);
